name: inception

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    restart: on-failure
    env_file:
      - ./environment/database.env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    container_name: wordpress
    restart: on-failure
    env_file:
      - ./.env
      - ./environment/database.env
      - ./environment/wordpress.env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    container_name: nginx
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro

      - type: bind
        source: ../certificates/inception.crt
        target: /etc/nginx/ssl/inception.crt
        read_only: true

      - type: bind
        source: ../certificates/inception.key
        target: /etc/nginx/ssl/inception.key
        read_only: true
    networks:
      - inception

  adminer:
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    image: adminer:inception
    container_name: adminer
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tsargsya/data/mariadb

  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tsargsya/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt

  db_password:
    file: ../secrets/db_password.txt

  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    driver: bridge